openapi: 3.0.3
info:
  title: 멀티테넌트 기업용 홈페이지 - 일반 사용자 API
  description: 일반 사용자가 기업 홈페이지를 조회하는 API
  version: 1.0.0
servers:
  - url: https://example.com
    description: 프로덕션 서버
  - url: http://localhost:8080
    description: 개발 서버

tags:
  - name: Company
    description: 기업 정보 조회
  - name: Board
    description: 게시판 조회
  - name: FAQ
    description: FAQ 조회
  - name: QnA
    description: QnA 조회 및 질문 등록
  - name: YouTube
    description: 유튜브 영상 조회
  - name: Product
    description: 상품 조회

paths:
  /{companyCode}:
    get:
      tags:
        - Company
      summary: 기업 홈페이지 메인 페이지
      description: 특정 기업의 메인 페이지를 렌더링한다.
      operationId: getCompanyHome
      parameters:
        - name: companyCode
          in: path
          required: true
          description: 기업 코드
          schema:
            type: string
            example: company-a
      responses:
        '200':
          description: HTML 페이지 반환
          content:
            text/html:
              schema:
                type: string
        '404':
          description: 기업을 찾을 수 없음
          content:
            text/html:
              schema:
                type: string

  /{companyCode}/about:
    get:
      tags:
        - Company
      summary: 회사 소개 페이지
      description: 기업의 상세 정보를 표시한다.
      operationId: getCompanyAbout
      parameters:
        - name: companyCode
          in: path
          required: true
          description: 기업 코드
          schema:
            type: string
            example: company-a
      responses:
        '200':
          description: HTML 페이지 반환
          content:
            text/html:
              schema:
                type: string
        '404':
          description: 기업을 찾을 수 없음

  /{companyCode}/boards/{boardType}:
    get:
      tags:
        - Board
      summary: 게시판 목록 조회
      description: 특정 게시판의 게시글 목록을 페이징하여 조회한다.
      operationId: getBoardList
      parameters:
        - name: companyCode
          in: path
          required: true
          description: 기업 코드
          schema:
            type: string
            example: company-a
        - name: boardType
          in: path
          required: true
          description: 게시판 타입
          schema:
            type: string
            enum: [notice, press, recruit]
            example: notice
        - name: page
          in: query
          description: 페이지 번호 (0부터 시작)
          schema:
            type: integer
            default: 0
            example: 0
        - name: size
          in: query
          description: 페이지 크기
          schema:
            type: integer
            default: 10
            example: 10
        - name: sort
          in: query
          description: 정렬 기준
          schema:
            type: string
            enum: [latest, views]
            default: latest
      responses:
        '200':
          description: HTML 페이지 반환
          content:
            text/html:
              schema:
                type: string
        '404':
          description: 기업 또는 게시판을 찾을 수 없음

  /{companyCode}/boards/{boardType}/posts/{postId}:
    get:
      tags:
        - Board
      summary: 게시글 상세 조회
      description: 특정 게시글의 상세 정보를 조회한다. 조회수가 1 증가한다.
      operationId: getPostDetail
      parameters:
        - name: companyCode
          in: path
          required: true
          description: 기업 코드
          schema:
            type: string
            example: company-a
        - name: boardType
          in: path
          required: true
          description: 게시판 타입
          schema:
            type: string
            example: notice
        - name: postId
          in: path
          required: true
          description: 게시글 ID
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: HTML 페이지 반환
          content:
            text/html:
              schema:
                type: string
        '404':
          description: 게시글을 찾을 수 없음

  /{companyCode}/faq:
    get:
      tags:
        - FAQ
      summary: FAQ 목록 조회
      description: 특정 기업의 FAQ 목록을 카테고리별로 조회한다.
      operationId: getFaqList
      parameters:
        - name: companyCode
          in: path
          required: true
          description: 기업 코드
          schema:
            type: string
            example: company-a
        - name: category
          in: query
          description: 카테고리 필터 (선택사항)
          schema:
            type: string
            example: 일반
        - name: search
          in: query
          description: 검색 키워드 (선택사항)
          schema:
            type: string
            example: 영업시간
      responses:
        '200':
          description: HTML 페이지 반환
          content:
            text/html:
              schema:
                type: string
        '404':
          description: 기업을 찾을 수 없음

  /{companyCode}/qna:
    get:
      tags:
        - QnA
      summary: QnA 목록 조회
      description: 특정 기업의 QnA 목록을 조회한다.
      operationId: getQnaList
      parameters:
        - name: companyCode
          in: path
          required: true
          description: 기업 코드
          schema:
            type: string
            example: company-a
        - name: page
          in: query
          description: 페이지 번호 (0부터 시작)
          schema:
            type: integer
            default: 0
            example: 0
        - name: size
          in: query
          description: 페이지 크기
          schema:
            type: integer
            default: 10
            example: 10
      responses:
        '200':
          description: HTML 페이지 반환
          content:
            text/html:
              schema:
                type: string
        '404':
          description: 기업을 찾을 수 없음

    post:
      tags:
        - QnA
      summary: QnA 질문 등록
      description: 일반 사용자가 로그인 없이 질문을 등록한다. reCAPTCHA 검증 포함.
      operationId: createQna
      parameters:
        - name: companyCode
          in: path
          required: true
          description: 기업 코드
          schema:
            type: string
            example: company-a
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - questionTitle
                - questionBody
                - askerEmail
                - recaptchaToken
              properties:
                questionTitle:
                  type: string
                  description: 질문 제목
                  example: 상담 문의
                questionBody:
                  type: string
                  description: 질문 내용
                  example: 제품 구매 관련하여 상담받고 싶습니다.
                askerEmail:
                  type: string
                  format: email
                  description: 질문자 이메일
                  example: user@example.com
                recaptchaToken:
                  type: string
                  description: reCAPTCHA v3 토큰
                  example: 03AGdBq27...
      responses:
        '302':
          description: 질문 등록 성공, QnA 목록 페이지로 리다이렉트
        '400':
          description: 입력 검증 실패 또는 스팸 의심
          content:
            text/html:
              schema:
                type: string
        '404':
          description: 기업을 찾을 수 없음

  /{companyCode}/qna/{qnaId}:
    get:
      tags:
        - QnA
      summary: QnA 상세 조회
      description: 특정 QnA의 질문과 답변을 조회한다.
      operationId: getQnaDetail
      parameters:
        - name: companyCode
          in: path
          required: true
          description: 기업 코드
          schema:
            type: string
            example: company-a
        - name: qnaId
          in: path
          required: true
          description: QnA ID
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: HTML 페이지 반환
          content:
            text/html:
              schema:
                type: string
        '404':
          description: QnA를 찾을 수 없음

  /{companyCode}/videos:
    get:
      tags:
        - YouTube
      summary: 유튜브 영상 목록 조회
      description: 특정 기업의 유튜브 영상 목록을 조회한다.
      operationId: getVideoList
      parameters:
        - name: companyCode
          in: path
          required: true
          description: 기업 코드
          schema:
            type: string
            example: company-a
      responses:
        '200':
          description: HTML 페이지 반환
          content:
            text/html:
              schema:
                type: string
        '404':
          description: 기업을 찾을 수 없음

  /{companyCode}/products:
    get:
      tags:
        - Product
      summary: 상품 목록 조회
      description: 특정 기업의 상품 목록을 카테고리별로 조회한다.
      operationId: getProductList
      parameters:
        - name: companyCode
          in: path
          required: true
          description: 기업 코드
          schema:
            type: string
            example: company-a
        - name: category
          in: query
          description: 카테고리 필터 (선택사항)
          schema:
            type: string
            example: IT 서비스
      responses:
        '200':
          description: HTML 페이지 반환
          content:
            text/html:
              schema:
                type: string
        '404':
          description: 기업을 찾을 수 없음

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
